/*
 * RCC.c
 *
 *  Created on: Dec 18, 2024
 *      Author: FlY DeN
 */

#include "RCC.h"

void CMSIS_Clock_Config() {
	//Configure flash WS and VOS
	MODIFY_REG(FLASH->ACR, FLASH_ACR_LATENCY_Msk,
			0b000 << FLASH_ACR_LATENCY_Pos);
	MODIFY_REG(PWR->CR1, PWR_CR1_VOS_Msk, 0b01 << PWR_CR1_VOS_Pos);

	//Configure RCC
	CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
	CLEAR_BIT(RCC->CR, RCC_CR_CSSON);
	CLEAR_BIT(RCC->CR, RCC_CR_HSEON);
	CLEAR_BIT(RCC->CR, RCC_CR_HSEBYP);
	SET_BIT(RCC->CR, RCC_CR_HSION);
	while (READ_BIT(RCC->CR, RCC_CR_HSIRDY) == RESET);
	MODIFY_REG(RCC->CR, RCC_CR_HSIDIV_Msk, 0b000 << RCC_CR_HSIDIV_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE_Msk, 0b0000 << RCC_CFGR_HPRE_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE_Msk, 0b000 << RCC_CFGR_PPRE_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SW_Msk, 0b000 << RCC_CFGR_SW_Pos);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_SWS_Msk, 0b000 << RCC_CFGR_SWS_Pos);
	//Configure PLL
//	CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
//	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLM_Msk, 0b011 << RCC_PLLCFGR_PLLM_Pos);
//	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLN_Msk, 0x3F << RCC_PLLCFGR_PLLN_Pos);
//	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLR_Msk, 0b011 << RCC_PLLCFGR_PLLR_Pos);
//	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_Msk, 0b10 << RCC_PLLCFGR_PLLSRC_Pos);
//	SET_BIT(RCC->PLLCFGR, RCC_PLLCFGR_PLLREN);
//	SET_BIT(RCC->CR, RCC_CR_PLLON);
//	while (READ_BIT(RCC->CR, RCC_CR_PLLRDY) == RESET);

//configure LSI/RTC
	SET_BIT(RCC->CSR,RCC_CSR_LSION);
	while (READ_BIT(RCC->CSR, RCC_CSR_LSIRDY) == RESET);
	SET_BIT(RCC->BDCR, RCC_BDCR_BDRST);
	CLEAR_BIT(RCC->BDCR, RCC_BDCR_BDRST);
	MODIFY_REG(RCC->BDCR, RCC_BDCR_RTCSEL_Msk, 0b10 << RCC_BDCR_RTCSEL_Pos);
	SET_BIT(RCC->BDCR, RCC_BDCR_RTCEN);
}

